### ISSUE TITLE
[Suggestion] A turtle upgrade that applies silk touch to the blocks the turtle mines.

### ISSUE THREAD

**Issue by Darkodaaa** [SwitchCraftCC/sc-goodies#43]

**Comment by piprett** [comment]
You can use kinetic augment with silk touch pickaxe.

**Comment by Lemmmy** [comment]
As Erb3 said, the current way to get tool-host-like behavior in the SC3 modpack is to use Plethora's Kinetic Augment. Let us know if you have any issues with that.
