### ISSUE TITLE
[BUG] Iron, Gold, Diamond Shulkers dont display their display names at the top, and the GUIs are glitchy

### ISSUE THREAD

**Issue by stealthy-coder** [SwitchCraftCC/sc-goodies#47]
So in regular shulker boxes, they show the Display name at the top and the gui fits atleast in my monitor (_FOV: Normal, GuiScale: 4, Fullscreen: OFF_) [IMAGE](https://i.imgur.com/ogQq2c1.png),
but **GOLD, DIAMOND** shulker boxes are slightly are off screen, and **DO NOT** show their display names (_IRON shulker boxes fit_), in other GuiScales (_1,2,3_), they fit, 
however they still dont show their titles. 
[IRON](https://i.imgur.com/59JK3tl.png), [GOLD](https://i.imgur.com/1rDnpiw.png), [DIAMOND](https://i.imgur.com/yJaKACg.png)

_If anyone needs anymore INFO, ask, ill be able to provide it._

**Comment by Lemmmy** [comment]
why are you shouting

**Comment by Lemmmy** [comment]
This is probably a wontfix. The current behavior is consistent with cpw's ironchest mod. As you noticed, on some screen sizes it's already hard enough to fit that many slots on-screen, which is why the container labels were omitted.
