### ISSUE TITLE
Magnets attempt to pull items into full inventories if other slots are empty

### ISSUE THREAD

**Issue by Allymonies** [SwitchCraftCC/sc-goodies#5]
Magnets will not attempt to pull items into a completely full inventory (full main inventory, full offhand, full armor slots), however, if a slot not in the main inventory is empty (i.e., an offhand or armor slot), the magnet will attempt to bring the item in even though it cannot be picked up, leading to the item to hover around the player. With many items, this can cause floating "orbs" of items following the player:
![21n6c 1](https://user-images.githubusercontent.com/7727003/212993275-ce859e8d-39e6-4e5e-8a9a-db10f9d7e86c.png)

**Comment by Lemmmy** [comment]
![image](https://user-images.githubusercontent.com/858456/212993528-7dde2402-0bbb-4f3a-839f-3b680284eb5b.png)

anyone remember this beta 1.8 pre-release bug?

**Comment by hugeblank** [comment]
I found that this was still happening with 3d prints, I assume it's because they share the same identifier as items in my inventory?

**Comment by Lemmmy** [comment]
Are the prints unique or identical?

**Comment by hugeblank** [comment]
From what I can recollect, no they were all different.
