### ISSUE TITLE
[Suggestion] Bees can duplicate flowers on pollination

### ISSUE THREAD

**Issue by Magicmaan** [SwitchCraftCC/sc-goodies#55]
Why?
For the general player - access to dyes easier, useful for expansion and various crafting recipes
For me - I like building, I like flowers.

And imo, it fits more inline with how bees actually work in real life, since they go around spreading flower pollen, which makes more flowers grow.

How would this work?
On pollination of the bee, it has a chance to drop an extra of that flower, drop on the block.

**Comment by scmcgowen** [comment]
Spreading pollen doesn’t cause flowers to grow, it causes them to make seeds and then later disperse them to cause new plants to grow which then grow flowers and repeat the cycle

But the suggestion is a neat idea (or you could use bonemeal from a skeleton farm)

**Comment by Magicmaan** [comment]
don't ruin the idea :( I just want free flowers man
