### ISSUE TITLE
Replacing grass with concrete slabs always results in the slab going on the bottom half of the block

### ISSUE THREAD

**Issue by WindClan** [SwitchCraftCC/sc-goodies#60]
Reproduction steps:
1. get an area full of tall grass
2. try and replace it with a slab on the top half of a block

Expected: The slab goes on the top half of the block
Result: The slab always goes on the bottom of the block

**Comment by Lemmmy** [comment]
Sorry, I don't quite understand, could you share a video of the problem? 

![image](https://github.com/SwitchCraftCC/sc-goodies/assets/858456/4d114ec7-5628-49c4-aa0c-e795cfcce58f)
With this setup, placing both a wood slab and a concrete slab 'underneath' the leaves and 'aside' the grass block (even though, in both cases, the raycast is targeting the top half of the tall grass) result in the same behavior - the slab being placed in the top half. The behaivor also seems consistent with vanilla. The same is true if I try to target the bottom tall grass block.

**Comment by Lemmmy** [comment]
@notbronwyn hi, just bumping this because I'm still not sure what the issue report is about. Is this still an issue?

**Comment by WindClan** [comment]
I have no memory of this and dont know what i did to have this issue so im assuming it isnt
