### ISSUE TITLE
Framed magnets do not work

### ISSUE THREAD

**Issue by khankul** [SwitchCraftCC/sc-goodies#61]
Magnets placed in frames do not prevent the magnets worn by players from attracting items.

https://github.com/SwitchCraftCC/sc-goodies/assets/93801865/8360adfe-d2f4-4608-9323-797f3a54f2e2

**Comment by Wojbie** [comment]
I am sorry I am having issues parsing what you are showing in that video due to amount of shaking? Is magnet never deactivated, you are doing something to reactivate it or is it showing as deactivated but still magnetic?

**Comment by khankul** [comment]
I walk into a magnet deactivation zone (due to the magnet in the frame) with an enabled magnet, and it doesn't deactivate it. It does show that it's deactivated but it still works.
