### ISSUE TITLE
[Suggestion] Renewable Gravel/Sand

### ISSUE THREAD

**Issue by powerboat9** [SwitchCraftCC/sc-goodies#62]
This would reduce the need for players to quarry the landscape for sand/gravel, and would make clay and dirt renewable as well.

1. Perhaps a machine which converts cobblestone to gravel or sand using fire charges as fuel, kind of like brewing stands post-1.9?
2. Perhaps upgraded fire charges, which when shot through a dispenser, produce a new type of fireball? One which converts nearby cobblestone into sand/gravel with a certain probability per block before exploding?
3. Perhaps a tool which "grinds down" blocks you use it on, but has low durability, requires iron + gold to craft, and can't accept mending?
4. Perhaps a plow-like block which acts kind of like https://ftb.fandom.com/wiki/Iron_Rod_(Quark) but can only move forward if it can grind down the block in front of it and then move that block to the side? Maybe it could also move sand to the side without grinding it down further?

**Comment by Kan18** [comment]
Gravel is already renewable via piglin trading, and I believe this is where most gravel traded on SC comes from nowadays. In my opinion there's enough sand in the world so as to not necessitate an extra feature to generate it (sand is technically renewable via wandering traders, although nobody ever does this)
