### ISSUE TITLE
[Suggestion] Using a gold ingot in a personal Ender Storage will turn it to the public variant

### ISSUE THREAD

**Issue by kristibektashi** [SwitchCraftCC/sc-goodies#7]
Gold ingot makes the most sense for this since the handle is gold in the public variant

**Comment by Lemmmy** [comment]
The diamond is 'consumed' by the Ender Storage when you use it on the handle, but you can retrieve it back by shift+clicking the handle again, which will of course make it a public chest again.

https://github.com/SwitchCraftCC/sc-goodies/blob/74c4304ea0273db2652dcb887d4e972686062445/src/main/kotlin/io/sc3/goodies/enderstorage/EnderStorageBlock.kt#L129-L143

**Comment by kristibektashi** [comment]
> The diamond is 'consumed' by the Ender Storage when you use it on the handle, but you can retrieve it back by shift+clicking the handle again, which will of course make it a public chest again.
> 
> https://github.com/SwitchCraftCC/sc-goodies/blob/74c4304ea0273db2652dcb887d4e972686062445/src/main/kotlin/io/sc3/goodies/enderstorage/EnderStorageBlock.kt#L129-L143

How was I supposed to know that lol?

**Comment by Lemmmy** [comment]
By asking (which you did so I answered), waiting for me to finish writing the docs, checking the code, or knowing that it’s the same as the 1.12 mod
